spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7a6e6a24be7d654a83ade131369d2ae4
            client-secret: cCXhNRlcYq5mCh6Pxjg6OXP5xVPnpgSI
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  application:
    name: login

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?serverTimezone=Asia/Seoul
    username: root
    password: 251414

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.springframework.security: DEBUG

